#:schema node_modules/wrangler/config-schema.json
name = "short"
main = "src/index.ts"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "go.emil.zip", custom_domain = true }
]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[[kv_namespaces]]
binding = "SHORTENER_STORE"
id = "24aa853207724acab01b4518771bf279"
